# Generated by Django 5.2 on 2026-04-17 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'authority',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='fullName', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.TextField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RoleAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authority', models.ForeignKey(db_column='authority_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_authorities', to='users.authority')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_authorities', to='users.role')),
            ],
            options={
                'db_table': 'role_authority',
                'unique_together': {('role', 'authority')},
            },
        ),
    ]
