name: hpa-postgres

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: hpa-postgres
    environment:
      POSTGRES_DB: hpa
      POSTGRES_USER: hpa
      POSTGRES_PASSWORD: hpa
    ports:
      - "5432:5432"
