# Generated by Django 5.2 on 2026-04-17 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('accuracy', models.FloatField()),
                ('dataset_size', models.BigIntegerField(db_column='datasetSize')),
                ('success', models.BooleanField(default=False)),
                ('model_path', models.CharField(blank=True, db_column='modelPath', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=False)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'run_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(db_column='idL', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft_living', models.IntegerField()),
                ('sqft_lot', models.IntegerField()),
                ('floors', models.FloatField()),
                ('waterfront', models.BooleanField(default=False)),
                ('view', models.IntegerField(default=0)),
                ('condition', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('sqft_above', models.IntegerField()),
                ('sqft_basement', models.IntegerField()),
                ('yr_built', models.IntegerField()),
                ('yr_renovated', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('sqft_living15', models.IntegerField()),
                ('sqft_lot15', models.IntegerField()),
            ],
            options={
                'db_table': 'training_data',
            },
        ),
    ]
