# Generated by Django 5.2 on 2026-05-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdata',
            options={'managed': False},
        ),
    ]
